#指定注册中心地址
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://192.168.1.191:8660/eureka/
#  instance:
#    instance-id: ${spring.cloud.client.ip-address}:${server.port}
#    prefer-ip-address: true
server:
  port: 9001
spring:
#  servlet:
  #    multipart:
  #      max-file-size:  100MB
  #      max-request-size: 100MB
  #  application:
  #    name: dt-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    #120.79.153.77 192.168.1.191
    url: jdbc:mysql://192.168.1.230:3306/rb_warehouse_1001?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    ##################    连接池配置    ################
    initialSize: 20   #连接池建立时创建的初始化连接数
    maxActive: 100 #连接池中最大的活跃连接数
    minIdle: 5 #连接池中最小的活跃连接数
    maxWait: 60000 # 配置获取连接等待超时的时间
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    #打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    ################Redis
    #连接第0个库
  redis:
    database: 0
    #连接的地址
    host: 192.168.1.230
    #超时时间：单位ms
    timeout: 5000
    #端口号
    port: 6379
    ##最大连接数：能够同时建立的“最大链接个数”
    pool:
      maxActive: 2000
      #最大空闲数：空闲链接数大于maxIdle时，将进行回收
      maxIdle: 200
      #最小空闲数：低于minIdle时，将创建新的链接
      minIdle: 200
      #最大等待时间：单位ms
      maxWait: 1000
      #服务的名称
#修改调用超时时间
#feign:
#  hystrix:
#    enabled: true
#  client:
#    com.wh.config:
#      default:
#        connectTimeout: 2000
#        readTimeout: 1000
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  mapper-locations: classpath*:mapper/**/*.xml  #配置映射xml地址
